# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: ChatBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    pdo:
        class: PDO
        arguments:
            - "mysql:dbname=%database_name%"
            - %database_user%
            - %database_password%
        calls:
            - [setAttribute, [3, 2]]

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments: [@pdo, %session.db_options%]

    chat.component.message:
        class:    ChatBundle\Component\MessageComponent
        calls:
            - [ setContainer, [@service_container] ]

    chat.handler:
        class:    ChatBundle\Handler\ChatHandler
        arguments: [ @chat.component.message, @chat.logger ]
        calls:
            - [setDoctrine, [@doctrine]]

    chat.session.provider:
        class:     Ratchet\Session\SessionProvider
        arguments:  [@chat.handler, @session.handler]

    chat.message.manager:
        class:    ChatBundle\Entity\MessageManager
        arguments:  [ @doctrine.orm.entity_manager ]

    chat.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@chat.logger_handler]]

    chat.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.chat.log, 200]
