services:
    chat.admin.user_manager:
        class: ChatBundle\Model\UserAdminManager
        arguments:
            - @doctrine
        calls:
            - [ setUserManager, [@fos_user.user_manager]]

    sonata.admin.user:
        class: ChatBundle\Admin\UserAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Admin"
              label: "User"
        arguments:
            - ~
            - ChatBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [ChatBundle]]
            - [ setModelManager, [@chat.admin.user_manager]]

    sonata.admin.room:
        class: ChatBundle\Admin\RoomAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Admin"
              label: "Room"
        arguments:
            - ~
            - ChatBundle\Entity\Room
            - ~
        calls:
            - [ setTranslationDomain, [ChatBundle]]
