#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          chat
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network $time mysql
# Should-Stop:       $network $time mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the chat database server daemon
# Description:       Controls the main Chat daemon "chat"
### END INIT INFO
#
set -e
set -u
${DEBIAN_SCRIPT_DEBUG:+ set -v -x}

. /lib/lsb/init-function`s

SELF=$(cd $(dirname $0); pwd -P)/$(basename $0)

# priority can be overriden and "-s" adds output to stderr
ERR_LOGGER="logger -p daemon.err -t /etc/init.d/chat -i"

# Safeguard (relative paths, core dumps..)
cd /
umask 077

chat_status () {

    ps_alive=0
    pidfile="/var/run/chat.pid"
    if [ -f "$pidfile" ] && ps `cat $pidfile` >/dev/null 2>&1; then ps_alive=1; fi

    if [ "$1" = "check_alive"  -a  $ps_alive = 1 ] ||
        [ "$1" = "check_dead"   -a  $ps_alive = 0 ]; then
    return 0 # EXIT_SUCCESS
    else
        return 1 # EXIT_FAILURE
    fi
}

case "${1:-''}" in
'start')
    php /var/www/chat/app/console chat:start 
;;

'stop')
    php /var/www/chat/app/console chat:stop
;;

'restart')
set +e; $SELF stop; set -e
$SELF start 
;;

'status')
    if chat_status check_alive nowarn; then
        log_action_msg "Chat is working."
    else
        log_action_msg "Chat is stopped."
    fi
;;
*)
echo "Usage: $SELF start|stop|restart|status"
exit 1
;;
esac


